config/routes.rb
Voyage::Application.routes.draw do

  resources :histories

  get "mobile/index"

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
             controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :comments

  resources :tours

  get "mobile/index"

  get "mobile/identities"

  get "mobile/items"

  get "mobile/floors"

  get "mobile/museums"

  get "mobile/finish"

  get "mobile/create_comment"

  namespace :admin do
    get "dashboard/index"
    root :to => "dashboard#index"

    resources :pieces

    resources :tours

    resources :users

    resources :countries

    resources :locations, :controller => "countries"

    resources :galleries

    resources :creators

    resources :comments

    resources :tour_histories

    resources :histories

  end

  root :to => 'mobile#index'

end

app/models/piece.rb
class Piece < ActiveRecord::Base
  belongs_to :creator
  belongs_to :gallery

  #has_many :connections
  has_many :informations
  has_many :comments
  has_many :likes
  has_many :questions, :dependent => :destroy
  has_many :answers, :through => :questions
  has_many :tour_items
  has_many :tours, :through => :tour_items

  has_and_belongs_to_many :connections

  scope :inExhibition, where(:exhibited => true)
  scope :notExhibited, where(:exhibited => false)

  attr_accessible :accession_number, :credit, :exhibited, :measurements, :medium, :title, :image, :image_content_type, :image_file_name, :image_file_size, :image_updated_at, :questions_attributes, :informations_attributes, :creator_id, :gallery_id, :location, :connections_attributes, :tour_attributes, :museum, :latin, :period, :collection_number, :description, :artist

  validates :title, :presence => true

  #default_scope order('title ASC')

  has_attached_file :image, styles: {
      thumb:  '50x50>',
      medium: '100x100>',
      large:  '120x120>'
  }

  accepts_nested_attributes_for :questions, :allow_destroy => true
  accepts_nested_attributes_for :informations, :allow_destroy => true

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/admin/pieces_controller.rb
class Admin::PiecesController < Admin::ResourceController

  helper_method :sort_column, :sort_direction

  # GET /pieces
  # GET /pieces.json
  def index
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @pieces = Piece.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pieces }
    end
  end

  # GET /pieces/1
  # GET /pieces/1.json
  def show
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @piece = Piece.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/new
  # GET /pieces/new.json
  def new
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @piece = Piece.new
    @creators = Creator.find(:all)
    @galleries = Gallery.find(:all)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/1/edit
  def edit
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @piece = Piece.find(params[:id])

    @creators = Creator.find(:all)
    @galleries = Gallery.find(:all)
  end

  # POST /pieces
  # POST /pieces.json
  def create
    @piece = Piece.new(params[:piece])

    respond_to do |format|
      if @piece.save
        format.html { redirect_to [:admin, @piece], notice: 'Piece was successfully created.' }
        format.json { render json: @piece, status: :created, location: @piece }
      else
        format.html { render action: "new" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pieces/1
  # PUT /pieces/1.json
  def update
    @piece = Piece.find(params[:id])

    respond_to do |format|
      if @piece.update_attributes(params[:piece])
        format.html { redirect_to [:admin, @piece], notice: 'Piece was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1
  # DELETE /pieces/1.json
  def destroy
    @piece = Piece.find(params[:id])
    @piece.destroy

    respond_to do |format|
      format.html { redirect_to admin_pieces_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Piece.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  # GET /pieces
  # GET /pieces.json
  def index
    @pieces = Piece.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pieces }
    end
  end

  # GET /pieces/1
  # GET /pieces/1.json
  def show
    @piece = Piece.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/new
  # GET /pieces/new.json
  def new
    @piece = Piece.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/1/edit
  def edit
    @piece = Piece.find(params[:id])
  end

  # POST /pieces
  # POST /pieces.json
  def create
    @piece = Piece.new(params[:piece])

    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece, notice: 'Piece was successfully created.' }
        format.json { render json: @piece, status: :created, location: @piece }
      else
        format.html { render action: "new" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pieces/1
  # PUT /pieces/1.json
  def update
    @piece = Piece.find(params[:id])

    respond_to do |format|
      if @piece.update_attributes(params[:piece])
        format.html { redirect_to @piece, notice: 'Piece was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1
  # DELETE /pieces/1.json
  def destroy
    @piece = Piece.find(params[:id])
    @piece.destroy

    respond_to do |format|
      format.html { redirect_to pieces_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/pieces_helper.rb
module Admin::PiecesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/admin/pieces/_answer_fields.html.erb
<fieldset>
    <div class="partial_form">
        <label class="checkbox">
            <%= f.check_box :correct %> Correct
        </label>

        <%= f.label :content, "Answer" %>
        <%= f.text_field :content, :class => "input-xxlarge" %>
        <%= f.hidden_field :_destroy %>
        <%= link_to "Remove", "#", :class => "remove_fields" %><br>
    </div>
</fieldset>

app/views/admin/pieces/_form.html.erb
<%= form_for [:admin, @piece], :html => {:class => "form-horizontal", :multipart => true} do |f| %>
    <% if @piece.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

            <ul>
                <% @piece.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <fieldset>
        <legend>Piece</legend>

        <div class="control-group">
            <%= f.label :museum, :class => "control-label" %>
            <div class="controls">
                <%= f.select :museum, ['Art', 'Natural History'] %>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <%= f.check_box :exhibited %> Exhibited
                </label>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :title, "Title/Name", :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :title, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group natural_history">
            <%= f.label :latin, "Latin Name", :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :latin, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :image, :class => "control-label" %>
            <div class="controls">
                <%= f.file_field :image %>
            </div>
        </div>
        <div class="control-group art">
            <%= f.label :artist, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :artist, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group art">
            <%= f.label :creator, :class => "control-label" %>
            <div class="controls">
                <%= f.select :creator_id, Creator.all.collect {|p| [p.name, p.id]}, {:include_blank => true} %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :gallery, :class => "control-label" %>
            <div class="controls">
                <%= f.select :gallery_id, Gallery.all.collect {|g| [g.name, g.id]}, {:include_blank => true} %>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Location</label>
            <div class="controls">
                <%= f.text_field :location, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :period, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :period, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group art">
            <%= f.label :medium, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :medium, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group art">
            <%= f.label :measurements, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :measurements, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group art">
            <%= f.label :credit, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :credit, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group art">
            <%= f.label :accession_number, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :accession_number, :class => "input-xxlarge" %>
            </div>
        </div>

        <div class="control-group natural_history">
            <%= f.label :collection_number, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :collection_number, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group natural_history">
            <%= f.label :description, :class => "control-label" %>
            <div class="controls">
                <%= f.text_area :description, :rows => 3, :class => "input-xxlarge" %><br/>
            </div>
        </div>
    </fieldset>

    <% f.fields_for :questions do |builder| %>
        <%= render 'question_fields', :f => builder %>
    <% end %>

    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab1" data-toggle="tab">Questions</a></li>
            <li><a href="#tab2" data-toggle="tab">Informations</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <p>
                    (<a href="#" class="info_tip" data-toggle="popover" data-placement="right" data-content="Questions are used during the Voyage by the visitor to check-in into a specific piece." title="Questions">What is this?</a>)
                </p>
                <%= f.fields_for :questions do |builder| %>
                    <%= render 'question_fields', :f => builder %>
                <% end %>
                <%= link_to_add_fields "Add Question", f, :questions %>
            </div>
            <div class="tab-pane" id="tab2">
                <p>
                    (<a href="#" class="info_tip" data-toggle="popover" data-placement="right" data-content="These are the information which will be shown to the visitor prior and during the visit at the museum." title="Informations">What is this?</a>)
                </p>
                <%= f.fields_for :informations do |builder| %>
                    <%= render 'information_fields', :f => builder %>
                <% end %>
                <%= link_to_add_fields "Add Information", f, :informations %>
            </div>
        </div>
    </div>

    <div class="control-group">
        <%= f.submit "Save", :class => "btn" %>
    </div>

<% end %>

app/views/admin/pieces/_question_fields.html.erb
<fieldset>
<div class="partial_form">
    <%= f.label :content, "Question" %>
    <%= f.text_field :content, :class => "input-xxlarge" %>
    <%= link_to "Remove", "#", :class => "remove_fields" %><br/>
    <%= f.hidden_field :_destroy %>
    <%= f.fields_for :answers do |builder| %>
        <%= render 'answer_fields', :f => builder %>
    <% end %>
    <%= link_to_add_fields "Add Answer", f, :answers %><br>
</div>
</fieldset>

app/views/admin/pieces/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', [:admin, @piece], "data-ajax" => "false" %> |
<%= link_to 'Back', admin_pieces_path, "data-ajax" => "false" %>

app/views/admin/pieces/index.html.erb
<h1>Pieces</h1>

<br>

<%= form_tag admin_pieces_path, :method => 'get' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil, :class => "btn" %>
    </p>
<% end %>


<% if @pieces.length == 0 %>
    <p>There are no pieces in the inventory.</p>
<% else %>

<table class="table table-bordered table-striped">
    <tr>
        <th><%= sortable "museum" %></th>
        <th><%= sortable "exhibited" %></th>
        <th><%= sortable "title" %></th>
        <th>Creator</th>
        <th>Gallery</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    <% @pieces.each do |piece| %>
        <tr>
            <td><%= piece.museum %></td>
            <td>
                <% if piece.exhibited %>
                    Yes
                <% else %>
                    No
                <% end %>
            </td>
            <td><%= piece.title %></td>
            <td><%= if piece.creator.nil? then "" else piece.creator.name end %></td>
            <td><%= if piece.gallery.nil? then "" else piece.gallery.name end %></td>
            <td style="text-align: center;"><%= link_to raw("<i class='icon-file'></i>"), [:admin, piece], "data-toggle" => "tooltip", "data-placement" => "right", :title => "View", :class => "tooltip_right" %></td>
            <td style="text-align: center;"><%= link_to raw("<i class='icon-pencil'></i>"), edit_admin_piece_path(piece), "data-toggle" => "tooltip", "data-placement" => "right", :title => "Edit", :class => "tooltip_right" %></td>
            <td style="text-align: center;"><%= link_to raw("<i class='icon-trash'></i>"), [:admin, piece], method: :delete, data: {confirm: 'Are you sure you want to delete this item? This action can NOT be reversed.' }, "data-toggle" => "tooltip", "data-placement" => "right", :title => "Delete", :class => "tooltip_right" %></td>
        </tr>
    <% end %>
</table>

<% end %>

<%= will_paginate @pieces %>

<br/>

<%= link_to 'New Piece', new_admin_piece_path, "data-ajax" => "false" %>

app/views/admin/pieces/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_pieces_path, "data-ajax" => "false" %>

app/views/admin/pieces/show.html.erb
<h1>Piece</h1>

<p id="notice"><%= notice %></p>
<div class="thumbnail">
<%= image_tag @piece.image.url(:large) if @piece.image.exists? %>
</div>
<table class="table table-bordered table-striped">
    <tr>
        <td>Museum</td>
        <td><%= @piece.museum %></td>
    </tr>
    <tr>
        <td>
            <% if @piece.museum == "Natural History" %>
                Name
            <% else %>
                Title
            <% end %>
        </td>
        <td><%= @piece.title %></td>
    </tr>
    <% if @piece.museum == "Natural History" %>
        <tr>
            <td>Latin Name</td>
            <td><%= @piece.latin %></td>
        </tr>
    <% end %>
    <tr>
        <td>Exhibited</td>
        <td>
            <% if @piece.exhibited %>
                Yes
            <% else %>
                No
            <% end %>
        </td>
    </tr>
    <% unless @piece.museum == "Natural History" %>
        <tr>
            <td>Artist</td>
            <td><%= @piece.artist %></td>
        </tr>
    <tr>
        <td>Creator</td>
        <td>
            <% unless @piece.creator.nil? %>
                <%= @piece.creator.name %>
            <% end %>
        </td>
    </tr>
    <% end %>
    <tr>
        <td>Gallery</td>
        <td>
            <% unless @piece.gallery.nil? %>
                <%= @piece.gallery.name %>
            <% end %>
        </td>
    </tr>
    <tr>
        <td>Location</td>
        <td><%= @piece.location %></td>
    </tr>
    <% if @piece.museum == "Natural History" %>
        <tr>
            <td>Period</td>
            <td><%= @piece.period %></td>
        </tr>
        <tr>
            <td>Collection number</td>
            <td><%= @piece.collection_number %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @piece.description %></td>
        </tr>
    <% else %>
    <tr>
        <td>Medium</td>
        <td><%= @piece.medium %></td>
    </tr>
    <tr>
        <td>Measurements</td>
        <td><%= @piece.measurements %></td>
    </tr>
    <tr>
        <td>Credit</td>
        <td><%= @piece.credit %></td>
    </tr>
    <tr>
        <td>Accession number</td>
        <td><%= @piece.accession_number %></td>
    </tr>
    <% end %>
</table>

<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Questions</a></li>
        <li><a href="#tab2" data-toggle="tab">Informations</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <% if @piece.questions.length > 0 %>
            <ol>
                <% for question in @piece.questions %>
                    <li>
                        <%= h question.content %>
                    </li>
                    <ul>
                        <% for answer in question.answers %>
                            <li>
                                <%= "[Correct] " if answer.correct %>
                                <%= answer.content %>
                            </li>
                        <% end %>
                    </ul>
                <% end %>
            </ol>
            <% else %>
            <p>No questions created.</p>
            <% end %>
        </div>
        <div class="tab-pane" id="tab2">
            <% if @piece.informations.length > 0 %>
            <ol>
                <% for information in @piece.informations %>
                    <li>
                        <ul>
                            <li>Before: <%= information.before %></li>
                            <li>After: <%= information.after %></li>
                        </ul>
                    </li>
                <% end %>
            </ol>
            <% else %>
                <p>No informations created.</p>
            <% end %>
        </div>
    </div>
</div>


<%= link_to 'Edit', edit_admin_piece_path(@piece), "data-ajax" => "false" %> |
<%= link_to 'Back', admin_pieces_path, "data-ajax" => "false" %>