config/routes.rb
Voyage::Application.routes.draw do

  resources :histories

  get "mobile/index"

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
             controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :comments

  resources :tours

  get "mobile/index"

  get "mobile/identities"

  get "mobile/items"

  get "mobile/floors"

  get "mobile/museums"

  get "mobile/finish"

  get "mobile/create_comment"

  namespace :admin do
    get "dashboard/index"
    root :to => "dashboard#index"

    resources :pieces

    resources :tours

    resources :users

    resources :countries

    resources :locations, :controller => "countries"

    resources :galleries

    resources :creators

    resources :comments

    resources :tour_histories

    resources :histories

  end

  root :to => 'mobile#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :pieces

  validates :name, :presence => true

  attr_accessible :about, :name, :order, :floor

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::ResourceController

  helper_method :sort_column, :sort_direction

  # GET /galleries
  # GET /galleries.json
  def index
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @galleries = Gallery.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "pieces"
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to admin_galleries_url, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to admin_galleries_url, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to admin_galleries_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Gallery.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/galleries/_form.html.erb
<%= form_for [:admin, @gallery], :html => {:class => "form-horizontal"} do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <fieldset>
        <legend>Gallery</legend>

        <div class="control-group">
            <%= f.label :name, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :name, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :order, :class => "control-label" %>
            <div class="controls">
                <%= f.number_field :order %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :floor, :class => "control-label" %>
            <div class="controls">
                <%= f.number_field :floor %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :about, :class => "control-label" %>
            <div class="controls">
                <%= f.text_area :about, :rows => 3, :class => "input-xxlarge" %>
            </div>
        </div>

    </fieldset>
    <div class="control-group">
        <%= f.submit "Save", :class => "btn" %>
    </div>

<% end %>

app/views/admin/galleries/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/index.html.erb
<h1>Galleries</h1>
<br>
<%= form_tag admin_galleries_path, :method => 'get' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil, :class => "btn" %>
    </p>
<% end %>

<% if @galleries.length == 0 %>
    <p>There are no galleries in the inventory.</p>
<% else %>

    <table class="table table-bordered table-striped">
        <tr>
            <th><%= sortable "name" %></th>
            <th>Order</th>
            <th><%= sortable "floor" %></th>
            <th>About</th>
            <th></th>
            <th></th>
        </tr>

        <% @galleries.each do |gallery| %>
            <tr>
                <td><%= gallery.name %></td>
                <td><%= gallery.order %></td>
                <td><%= gallery.floor %></td>
                <td><%= sanitize(truncate(gallery.about), :length => 150) %></td>
                <td style="text-align: center;"><%= link_to raw("<i class='icon-pencil'></i>"), edit_admin_gallery_path(gallery), "data-toggle" => "tooltip", "data-placement" => "right", :title => "Edit", :class => "tooltip_right" %></td>
                <td style="text-align: center;"><%= link_to raw("<i class='icon-trash'></i>"), [:admin, gallery], method: :delete, data: {confirm: 'Are you sure you want to delete this item? This action can NOT be reversed.' }, "data-toggle" => "tooltip", "data-placement" => "right", :title => "Delete", :class => "tooltip_right" %></td>
            </tr>
        <% end %>
    </table>
<% end %>

<%= will_paginate @galleries %>

<br/>

<%= link_to 'New Gallery', new_admin_gallery_path %>

app/views/admin/galleries/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gallery.name %>
</p>

<p>
  <b>Order:</b>
  <%= @gallery.order %>
</p>

<p>
    <b>Floor:</b>
    <%= @gallery.floor %>
</p>

<p>
  <b>About:</b>
  <%= @gallery.about %>
</p>


<%= link_to 'Edit', edit_admin_gallery_path(@gallery) %> |
<%= link_to 'Back', admin_galleries_path %>