config/routes.rb
Voyage::Application.routes.draw do

  resources :histories

  get "mobile/index"

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
             controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :comments

  resources :tours

  get "mobile/index"

  get "mobile/identities"

  get "mobile/items"

  get "mobile/floors"

  get "mobile/museums"

  get "mobile/finish"

  get "mobile/create_comment"

  namespace :admin do
    get "dashboard/index"
    root :to => "dashboard#index"

    resources :pieces

    resources :tours

    resources :users

    resources :countries

    resources :locations, :controller => "countries"

    resources :galleries

    resources :creators

    resources :comments

    resources :tour_histories

    resources :histories

  end

  root :to => 'mobile#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :piece
  belongs_to :category
  belongs_to :connection
  belongs_to :tour

  has_many :likes

  attr_accessible :content, :user_id, :piece_id, :category_id, :connection_id, :tour_id, :like_id, :approved

  scope :recent, :limit => 10, :order => 'created_at DESC'
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ResourceController
  # GET /comments
  # GET /comments.json
  def index
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @comments = Comment.paginate(:per_page => 10, :page => params[:all_page]).order("created_at desc")
    @comments_pieces = Comment.where("piece_id > 0").paginate(:per_page => 10, :page => params[:pieces_page]).order("created_at desc")
    @comments_tours = Comment.where("tour_id > 0").paginate(:per_page => 10, :page => params[:tours_page]).order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to admin_comments_url, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to admin_comments_url, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    unless @comment.present?
      @comment.destroy
    end

    respond_to do |format|
      format.html { redirect_to admin_comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  layout "mobile"

  # GET /comments
  # GET /comments.json
  def index
    @page = "comments"
    @comments = Comment.where('approved = ?', true).paginate(:per_page => 12, :page => params[:page]).order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comments_url, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  # POST /comments
  # POST /comments.json
  def add
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
       # format.html { redirect_to comments_url, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.erb
<%= form_for [:admin, @comment], :html => {:class => "form-horizontal"} do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <fieldset>
        <legend>Comment</legend>

        <div class="control-group">
            <%= f.label :content, :class => "control-label" %>
            <div class="controls">
                <%= f.text_area :content, :rows => 3, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :user_id, :class => "control-label" %>
            <div class="controls">
                <%= f.select :user_id, User.all.collect {|p| [p.email, p.id]}, {:include_blank => true} %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :connection_id, :class => "control-label" %>
            <div class="controls">
                <%= f.select :connection_id, Connection.all.collect {|p| [p.id, p.id]}, {:include_blank => true} %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :piece_id, :class => "control-label" %>
            <div class="controls">
                <%= f.select :piece_id, Piece.all.collect {|p| [p.title, p.id]}, {:include_blank => true} %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :tour_id, :class => "control-label" %>
            <div class="controls">
                <%= f.select :tour_id, Tour.all.collect {|p| [p.title, p.id]}, {:include_blank => true} %>
            </div>
        </div>

    </fieldset>

    <div class="control-group">
        <%= f.submit "Save", :class => "btn" %>
    </div>
<% end %>

app/views/admin/comments/edit.html.erb
<h1>Comment</h1>

<p>
    <b>User:</b>
    <%= link_to @comment.user.email, [:admin, @comment.user] if @comment.user %>
</p>
<% if @comment.piece %>
<p>
    <b>Piece:</b>
    <%= link_to @comment.piece.title, [:admin, @comment.piece] %>
</p>
<% end %>
<% if @comment.connection %>
<p>
    <b>Connection:</b>
    <%= link_to @comment.connection, [:admin, @comment.connection] %>
</p>
<% end %>
<% if @comment.tour %>
<p>
    <b>Tour:</b>
    <%= link_to @comment.tour.title, [:admin, @comment.tour] %>
</p>
<% end %>
<div class="well">
    <%= @comment.content %>
</div>
<%= form_for [:admin, @comment], :html => {:class => "form-horizontal"} do |f| %>
    <%= f.hidden_field :content %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :piece_id %>
    <%= f.hidden_field :connection_id %>
    <%= f.hidden_field :tour_id %>
    <label class="checkbox">
        <%= f.check_box :approved %> Approved
    </label>
    <div class="control-group">
        <%= f.submit "Save", :class => "btn" %>
    </div>
<% end %>


<%= link_to 'Back', admin_comments_path %>

app/views/admin/comments/index.html.erb
<h1>Comments</h1>

<% if @comments.length <= 0 %>
    <p>There are no comments.</p>
<% else %>

    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab1" data-toggle="tab">All</a></li>
            <li><a href="#tab2" data-toggle="tab">Pieces</a></li>
            <li><a href="#tab3" data-toggle="tab">Tours</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Approved</th>
                        <th>Content</th>
                        <th>User</th>
                        <th>Piece</th>
                        <th>Tour</th>
                        <th>Date</th>
                        <th></th>
                    </tr>

                    <% @comments.each do |comment| %>
                        <tr>
                            <td><%= comment.approved ? "Yes" : "No" %></td>
                            <td><%= comment.content %></td>
                            <td><%= comment.user.email if comment.user %></td>
                            <td>
                                <% if comment.piece %>
                                    <%= link_to comment.piece.title, [:admin, comment.piece] %>
                                <% end %>
                            </td>
                            <td>
                                <% if comment.tour %>
                                    <%= link_to comment.tour.title, [:admin, comment.tour] %>
                                <% end %>
                            </td>
                            <td><%= comment.created_at.to_time.strftime("%m/%d/%Y") %></td>
                            <td style="text-align: center;"><%= link_to raw("<i class='icon-file'></i>"), edit_admin_comment_path(comment), "data-toggle" => "tooltip", "data-placement" => "right", :title => "View", :class => "tooltip_right" %></td>
                        </tr>
                    <% end %>
                </table>
                <%= will_paginate @comments, :param_name => "all_page" %>
            </div>
            <div class="tab-pane" id="tab2">
                <% if @comments_pieces.length <= 0 %>
                    There are no comments for pieces
                <% else %>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Approved</th>
                            <th>Content</th>
                            <th>User</th>
                            <th>Piece</th>
                            <th>Date</th>
                            <th></th>
                        </tr>

                        <% @comments_pieces.each do |comment| %>
                            <tr>
                                <td><%= comment.approved ? "Yes" : "No" %></td>
                                <td><%= comment.content %></td>
                                <td><%= comment.user.email if comment.user %></td>
                                <td>
                                    <% if comment.piece %>
                                        <%= link_to comment.piece.title, [:admin, comment.piece] %>
                                    <% end %>
                                </td>
                                <td><%= comment.created_at.to_time.strftime("%m/%d/%Y") %></td>
                                <td style="text-align: center;"><%= link_to raw("<i class='icon-file'></i>"), edit_admin_comment_path(comment), "data-toggle" => "tooltip", "data-placement" => "right", :title => "View", :class => "tooltip_right" %></td>
                            </tr>
                        <% end %>
                    </table>
                    <%= will_paginate @comments_pieces, :param_name => "pieces_page" %>
                <% end %>
            </div>
            <div class="tab-pane" id="tab3">
                <% if @comments_tours.length <= 0 %>
                    There are no comments for pieces
                <% else %>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Approved</th>
                            <th>Content</th>
                            <th>User</th>
                            <th>Tour</th>
                            <th>Date</th>
                            <th></th>
                        </tr>

                        <% @comments_tours.each do |comment| %>
                            <tr>
                                <td><%= comment.approved ? "Yes" : "No" %></td>
                                <td><%= comment.content %></td>
                                <td><%= comment.user.email if comment.user %></td>
                                <td>
                                    <% if comment.tour %>
                                        <%= link_to comment.tour.title, [:admin, comment.tour] %>
                                    <% end %>
                                </td>
                                <td><%= comment.created_at.to_time.strftime("%m/%d/%Y") %></td>
                                <td style="text-align: center;"><%= link_to raw("<i class='icon-file'></i>"), edit_admin_comment_path(comment), "data-toggle" => "tooltip", "data-placement" => "right", :title => "View", :class => "tooltip_right" %></td>
                            </tr>
                        <% end %>
                    </table>
                    <%= will_paginate @comments_tours, :param_name => "tours_page" %>
                <% end %>
            </div>
        </div>
    </div>


<% end %>

app/views/admin/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/admin/comments/show.html.erb
<h1>Comment</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user %>
</p>

<p>
  <b>Piece:</b>
  <%= @comment.piece %>
</p>

<p>
  <b>Category:</b>
  <%= @comment.category %>
</p>

<p>
  <b>Connection:</b>
  <%= @comment.connection %>
</p>

<p>
  <b>Tour:</b>
  <%= @comment.tour %>
</p>

<div class="well">
    <%= @comment.content %>
</div>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>