config/routes.rb
Voyage::Application.routes.draw do

  resources :histories

  get "mobile/index"

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
             controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :comments

  resources :tours

  get "mobile/index"

  get "mobile/identities"

  get "mobile/items"

  get "mobile/floors"

  get "mobile/museums"

  get "mobile/finish"

  get "mobile/create_comment"

  namespace :admin do
    get "dashboard/index"
    root :to => "dashboard#index"

    resources :pieces

    resources :tours

    resources :users

    resources :countries

    resources :locations, :controller => "countries"

    resources :galleries

    resources :creators

    resources :comments

    resources :tour_histories

    resources :histories

  end

  root :to => 'mobile#index'

end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :user

  #has_many :tour_histories, :dependent => :destroy
  has_many :histories
  has_many :informations
  has_many :comments
  has_many :likes
  has_many :tour_items, :dependent => :destroy, :order => "position ASC"
  has_many :pieces, :through => :tour_items
  has_many :connections

  #has_and_belongs_to_many :pieces
  #has_and_belongs_to_many :categories

  attr_accessible :about, :curated, :image, :public, :title, :user_id, :image_file_name, :image_content_type, :image_file_size, :image_updated_at, :pieces_attributes, :informations_attributes, :tour_items_attributes, :connections_attributes

  validates :title, :presence => true

  has_attached_file :image, styles: {
      thumb:  '50x50>',
      medium: '100x100>',
      large:  '120x120>'
  }

  accepts_nested_attributes_for :pieces
  accepts_nested_attributes_for :tour_items, :allow_destroy => true
  accepts_nested_attributes_for :informations, :allow_destroy => true
  accepts_nested_attributes_for :connections, :allow_destroy => true

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::ResourceController

  helper_method :sort_column, :sort_direction

  # GET /tours
  # GET /tours.json
  def index
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "tours"
    @tours = Tour.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tours }
    end
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "tours"
    @tour = Tour.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tour }
    end
  end

  # GET /tours/new
  # GET /tours/new.json
  def new
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "tours"
    @tour = Tour.new
    @pieces = Piece.find(:all, :order => "title ASC")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tour }
    end
  end

  # GET /tours/1/edit
  def edit
    unless current_user.try(:admin?)
      redirect_to "/"
    end
    @page = "tours"
    @tour = Tour.find(params[:id])
    @pieces = Piece.find(:all, :order => "title ASC")
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(params[:tour])

    respond_to do |format|
      if @tour.save
        format.html { redirect_to [:admin, @tour], notice: 'Tour was successfully created.' }
        format.json { render json: @tour, status: :created, location: @tour }
      else
        format.html { render action: "new" }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tours/1
  # PUT /tours/1.json
  def update
    @tour = Tour.find(params[:id])

    respond_to do |format|
      if @tour.update_attributes(params[:tour])
        format.html { redirect_to [:admin, @tour], notice: 'Tour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy

    respond_to do |format|
      format.html { redirect_to admin_tours_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Tour.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  layout "mobile"

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.where('public = ?', true).order('title')
    @history = History.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tours }
    end
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    @tour = Tour.find(params[:id])
    @history = History.find(session[:history_id])
    @tour_items = @history.tour_items.sort_by{ |a| a.position.to_i }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tour }
    end
  end

  # GET /tours/new
  # GET /tours/new.json
  def new
    @tour = Tour.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tour }
    end
  end

  # GET /tours/1/edit
  def edit
    @tour = Tour.find(params[:id])
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(params[:tour])

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render json: @tour, status: :created, location: @tour }
      else
        format.html { render action: "new" }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tours/1
  # PUT /tours/1.json
  def update
    @tour = Tour.find(params[:id])

    respond_to do |format|
      if @tour.update_attributes(params[:tour])
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy

    respond_to do |format|
      format.html { redirect_to tours_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/admin/tours/_connection_fields.html.erb
<fieldset>
    <div class="partial_form">
        <%= f.label :description %>
        <%= f.text_area :description, :rows => 3, :class => "input-xxlarge" %>

        <%= f.collection_select :piece_ids, Piece.all, :id, :title, {:include_blank => 'None'}, {:multiple => true} %>

        <%= f.hidden_field :_destroy %>
        <%= link_to "Remove", "#", :class => "remove_fields" %><br/>


    </div>
</fieldset>

app/views/admin/tours/_form.html.erb
<%= form_for [:admin, @tour], :html => {:class => "form-horizontal"} do |f| %>
    <% if @tour.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

            <ul>
                <% @tour.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <fieldset>
        <legend>Tour</legend>
        <%= f.hidden_field :curated, :value => true %>
        <!-- TODO: Make save as user_id for logged in person -->
        <%= f.hidden_field :user_id, :value => 1 %>

        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <%= f.check_box :public %> Public
                </label>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :title, :class => "input-xxlarge" %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :image, :class => "control-label" %>
            <div class="controls">
                <%= f.file_field :image %>
            </div>
        </div>
        <div class="control-group">
            <%= f.label :about, :class => "control-label" %>
            <div class="controls">
                <%= f.text_area :about, :rows => 3, :class => "input-xxlarge" %>
            </div>
        </div>

    </fieldset>

    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab1" data-toggle="tab">Pieces</a></li>
            <li><a href="#tab2" data-toggle="tab">Connections</a></li>
            <li><a href="#tab3" data-toggle="tab">Informations</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <%= f.fields_for :tour_items, :html => {:class => "form-inline"} do |builder| %>
                    <%= render 'tour_item_fields', :f => builder %>
                <% end %>
                <%= link_to_add_fields "Add Piece", f, :tour_items %>
            </div>
            <div class="tab-pane" id="tab2">
                <p>
                    (<a href="#" class="info_tip" data-toggle="popover" data-placement="right" data-content="Connections are the interesting links between pieces in the tour that are shown to the visitor." title="Connections">What is this?</a>)
                </p>
                <%= f.fields_for :connections do |builder| %>
                    <%= render 'connection_fields', :f => builder %>
                <% end %>
                <%= link_to_add_fields "Add Connection", f, :connections %>
            </div>
            <div class="tab-pane" id="tab3">
                <p>
                    (<a href="#" class="info_tip" data-toggle="popover" data-placement="right" data-content="These are the information which will be shown to the visitor prior and during the visit at the museum." title="Informations">What is this?</a>)
                </p>
                <%= f.fields_for :informations do |builder| %>
                    <%= render 'information_fields', :f => builder %>
                <% end %>
                <%= link_to_add_fields "Add Information", f, :informations %>
            </div>
        </div>
    </div>

    <div class="control-group">
        <%= f.submit "Save", :class => "btn" %>
    </div>

<% end %>

app/views/admin/tours/_information_fields.html.erb
<fieldset>
    <div class="partial_form">
        <%= f.label :before, "Information Before" %>
        <%= f.text_area :before, :rows => 3, :class => "input-xxlarge" %><br>
        <%= f.label :after, "Information After" %>
        <%= f.text_area :after, :rows => 3, :class => "input-xxlarge" %><br/>
        <%= link_to "Remove", "#", :class => "remove_fields" %><br/>
        <%= f.hidden_field :_destroy %>
    </div>
</fieldset>

app/views/admin/tours/_piece_fields.html.erb
<fieldset>
    <div class="partial_form">
        <%= f.label :id, "Piece:" %>
        <%= f.collection_select :id, Piece.all, :id, :id %>
        <%= f.hidden_field :_destroy %>
        <%= link_to "Remove", "#", :class => "remove_fields" %><br>
    </div>
</fieldset>

app/views/admin/tours/_tour_item_fields.html.erb
<fieldset>
    <div class="partial_form">

        <table>
            <tr>
                <td>
                    <label class="checkbox">
                        <%= f.check_box :fixed %> Fixed
                    </label>
                </td>
                <td>&nbsp;&nbsp;&nbsp;</td>
                <td><%= f.label :piece_id, "Piece:" %></td>
                <td>
                    <%= f.select :piece_id, Piece.all.collect {|p| [p.title, p.id]}, {:include_blank => true} %>
                </td>
                <td>&nbsp;&nbsp;&nbsp;</td>
                <td><%= f.label :position, "   Position:   " %></td>
                <td><%= f.text_field :position %><br></td>
                <td>&nbsp;&nbsp;&nbsp;</td>
                <td>
                    <%= f.hidden_field :_destroy %>
                    <%= link_to "Remove", "#", :class => "remove_fields" %><br/>
                </td>
            </tr>
        </table>


    </div>
</fieldset>

app/views/admin/tours/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', [:admin, @tour] %> |
<%= link_to 'Back', admin_tours_path %>

app/views/admin/tours/index.html.erb
<h1>Tours</h1>

<br>

<%= form_tag admin_tours_path, :method => 'get' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil, :class => "btn" %>
    </p>
<% end %>

<% if @tours.length == 0 %>
    <p>There are no tours.</p>
<% else %>

    <table class="table table-bordered table-striped">
        <tr>
            <th><%= sortable "title" %></th>
            <th><%= sortable "curated" %></th>
            <th><%= sortable "public" %></th>
            <th>User</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        <% @tours.each do |tour| %>
            <tr>
                <td><%= tour.title %></td>
                <td><%= tour.curated ? "Yes" : "No" %></td>
                <td><%= tour.public ? "Yes" : "No" %></td>
                <td><%= tour.user.email if tour.user %></td>
                <td style="text-align: center;"><%= link_to raw("<i class='icon-file'></i>"), [:admin, tour], "data-toggle" => "tooltip", "data-placement" => "right", :title => "View", :class => "tooltip_right" %></td>
                <td style="text-align: center;"><%= link_to raw("<i class='icon-pencil'></i>"), edit_admin_tour_path(tour), "data-toggle" => "tooltip", "data-placement" => "right", :title => "Edit", :class => "tooltip_right" %></td>
                <td style="text-align: center;"><%= link_to raw("<i class='icon-trash'></i>"), [:admin, tour], method: :delete, data: {confirm: 'Are you sure you want to delete this item? This action can NOT be reversed.' }, "data-toggle" => "tooltip", "data-placement" => "right", :title => "Delete", :class => "tooltip_right" %></td>
            </tr>
        <% end %>
    </table>
<% end %>

<%= will_paginate @tours %>

<br/>

<%= link_to 'New Tour', new_admin_tour_path %>

app/views/admin/tours/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_tours_path %>

app/views/admin/tours/show.html.erb
<h1>Tour</h1>

<p id="notice"><%= notice %></p>

<div class="thumbnail">
    <%= image_tag @tour.image.url(:large) if @tour.image.exists? %>
</div>

<table class="table table-bordered table-striped">
    <tr>
        <td>Title</td>
        <td><%= @tour.title %></td>
    </tr>
    <tr>
        <td>Curated</td>
        <td><%= @tour.curated %></td>
    </tr>
    <tr>
        <td>Creator</td>
        <td><%= @tour.user.email if @tour.user %></td>
    </tr>
    <tr>
        <td>Public</td>
        <td><%= @tour.public %></td>
    </tr>
    <tr>
        <td>About</td>
        <td><%= @tour.about %></td>
    </tr>
</table>

<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Pieces</a></li>
        <li><a href="#tab2" data-toggle="tab">Connections</a></li>
        <li><a href="#tab3" data-toggle="tab">Informations</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <% if @tour.pieces.length > 0 %>
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Fixed</th>
                        <th>Piece</th>
                        <th>Position</th>
                    </tr>
                    <% for tour_item in @tour.tour_items %>
                        <tr>
                            <td><%= tour_item.fixed %></td>
                            <td><%= tour_item.piece.title unless tour_item.piece.nil? %></td>
                            <td><%= tour_item.position %></td>
                        </tr>
                    <% end %>
                </table>

            <% else %>
                <p>No pieces linked.</p>
            <% end %>
        </div>
        <div class="tab-pane" id="tab2">
            <% if @tour.connections.length > 0 %>
                <ul>
                    <% for connection in @tour.connections %>
                        <li><%= connection.description %></li>
                        <% if connection.pieces.length > 0 %>
                            <ul>
                                <% for piece in connection.pieces %>
                                    <li><%= piece.title %></li>
                                <% end %>
                            </ul>
                        <% end %>
                    <% end %>
                </ul>

            <% else %>
                <p>No connections.</p>
            <% end %>
        </div>
        <div class="tab-pane" id="tab3">
            <% if @tour.informations.length > 0 %>
                <ol>
                    <% for information in @tour.informations %>
                        <li>
                            <ul>
                                <li>Before: <%= information.before %></li>
                                <li>After: <%= information.after %></li>
                            </ul>
                        </li>
                    <% end %>
                </ol>
            <% else %>
                <p>No informations created.</p>
            <% end %>
        </div>
    </div>
</div>

<%= link_to 'Edit', edit_admin_tour_path(@tour) %> |
<%= link_to 'Back', admin_tours_path %>